language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
before_script:
  - npm i -g backstopjs
script:
  - yarn test
  - backstop reference
  - backstop test
  - backstop approve
before_deploy:
  - npm install netlify-cli -g
  - yarn build
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master
